# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fence.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fence.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66\x65nce.proto\"F\n\x0c\x46\x65nceRequest\x12\x0e\n\x06inside\x18\x01 \x01(\x03\x12\x12\n\nlast_image\x18\x02 \x01(\x0c\x12\x12\n\nthis_image\x18\x03 \x01(\x0c\"7\n\rFenceResponse\x12\r\n\x05\x61lert\x18\x01 \x01(\x08\x12\x17\n\x0f\x61lgorithm_image\x18\x02 \x01(\x0c\x32\x31\n\x05\x46\x65nce\x12(\n\x05\x46\x65nce\x12\r.FenceRequest\x1a\x0e.FenceResponse\"\x00\x62\x06proto3'
)




_FENCEREQUEST = _descriptor.Descriptor(
  name='FenceRequest',
  full_name='FenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inside', full_name='FenceRequest.inside', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_image', full_name='FenceRequest.last_image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='this_image', full_name='FenceRequest.this_image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=85,
)


_FENCERESPONSE = _descriptor.Descriptor(
  name='FenceResponse',
  full_name='FenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alert', full_name='FenceResponse.alert', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm_image', full_name='FenceResponse.algorithm_image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['FenceRequest'] = _FENCEREQUEST
DESCRIPTOR.message_types_by_name['FenceResponse'] = _FENCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FenceRequest = _reflection.GeneratedProtocolMessageType('FenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _FENCEREQUEST,
  '__module__' : 'fence_pb2'
  # @@protoc_insertion_point(class_scope:FenceRequest)
  })
_sym_db.RegisterMessage(FenceRequest)

FenceResponse = _reflection.GeneratedProtocolMessageType('FenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _FENCERESPONSE,
  '__module__' : 'fence_pb2'
  # @@protoc_insertion_point(class_scope:FenceResponse)
  })
_sym_db.RegisterMessage(FenceResponse)



_FENCE = _descriptor.ServiceDescriptor(
  name='Fence',
  full_name='Fence',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fence',
    full_name='Fence.Fence',
    index=0,
    containing_service=None,
    input_type=_FENCEREQUEST,
    output_type=_FENCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FENCE)

DESCRIPTOR.services_by_name['Fence'] = _FENCE

# @@protoc_insertion_point(module_scope)
