# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fence_pb2 as fence__pb2


class FenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fence = channel.unary_unary(
                '/Fence/Fence',
                request_serializer=fence__pb2.FenceRequest.SerializeToString,
                response_deserializer=fence__pb2.FenceResponse.FromString,
                )


class FenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Fence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fence': grpc.unary_unary_rpc_method_handler(
                    servicer.Fence,
                    request_deserializer=fence__pb2.FenceRequest.FromString,
                    response_serializer=fence__pb2.FenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Fence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fence(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fence/Fence',
            fence__pb2.FenceRequest.SerializeToString,
            fence__pb2.FenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
